### user registration
POST http://localhost:4000/auth-api/auth
Content-Type: application/json

{
    "username":"max",
    "email":"max@gmail.com",
    "number":393893123,
    "password":"max@123",
    "monthlyIncome":170000
}

### user login
POST http://localhost:4000/auth-api/auth/login
Content-Type: application/json

{
    "email":"max@gmail.com",
    "password":"max@123"
}

### posting the transactions data
POST http://localhost:4000/transactions-api/transactions
Content-Type: application/json

{
  "amount": 17000,
  "category": "Electronics",
  "date": "2026-03-16",
  "description": "Headphones purchased"
}

###getting transaction details
GET http://localhost:4000/transactions-api/transactions

###get transaction id
GET http://localhost:4000/transactions-api/transactions/69b8e7c29911ca129cf2acce

###edit transaction by id
PUT http://localhost:4000/transactions-api/transactions/69b8e7c29911ca129cf2acce
Content-Type: application/json

{
  "amount": 1500,
  "category": "Electronics",
  "date": "2026-03-16",
  "description": "earpods purchased"
}

### delete transaction
PATCH http://localhost:4000/transactions-api/transactions/69b8e7c29911ca129cf2acce
Content-Type: application/json

{
    "isActive":true
}

### getting analysis of the tranactions
GET http://localhost:4000/analytics-api/overall-analysis

### posting the emi details
POST http://localhost:4000/emi-api/emi
Content-Type: application/json

{
  "loanAmount": 1000000,
  "interestRate": 5.5,
  "tenureMonths": 15,
  "startDate": "2024-06-01",
  "dueDate": "2029-06-01"
}

### getting the emi details
GET http://localhost:4000/emi-api/emi

